{
 "title": "Corona",
 "description": "This dashboard will provide global COVID-19 information.",
 "time": { "from": "2020-01-27T10:03:19.657Z", "to": "2020-04-02T09:03:19.667Z" },
 "panels": [
  {
   "title": "Confirmed",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CoronaNew",
     "select": [
      [
       { "params": [ "Confirmed" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Deaths",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CoronaNew",
     "select": [
      [
       { "params": [ "Deaths" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Recovered",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CoronaNew",
     "select": [
      [
       { "params": [ "Recovered" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Remaining",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "covid19",
     "query": "SELECT sum(Confirmed)-sum(Recovered)-sum(Deaths) FROM \"covid19\".\"autogen\".\"CoronaNew\" WHERE $timeFilter GROUP BY time(24h) fill(null)\n",
     "select": [
      [
       { "params": [ "recovered" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Fatality Ratio",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Corona",
     "query": "SELECT sum(\"Deaths\") *100 / sum(\"Confirmed\") FROM \"covid19\".\"autogen\".\"CoronaNew\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Deaths" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [
         "*100 / sum(\"Confirmed\")"
        ],
        "type": "math"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Recovery Ratio",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CoronaNew",
     "query": "SELECT sum(\"Recovered\") * 100 / sum(\"Confirmed\" FROM \"covid19\".\"autogen\".\"Corona\" WHERE $timeFilter GROUP BY time(24h) fill(null)",
     "select": [
      [
       { "params": [ "Recovered" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [
         "* 100 / sum(\"Confirmed\")"
        ],
        "type": "math"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Confirmed",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 4 },
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "lat" ], "type": "tag" },
      { "params": [ "long" ], "type": "tag" }
     ],
     "measurement": "Corona",
     "query": "SELECT last(\"Confirmed\") AS \"metric\" FROM \"covid19\".\"autogen\".\"Corona\" WHERE $timeFilter GROUP BY \"country\", \"lat\", \"long\"",
     "select": [
      [
       { "params": [ "Confirmed" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "metric" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Deaths",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 4 },
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_location",
     "groupBy": [
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "lat" ], "type": "tag" },
      { "params": [ "long" ], "type": "tag" }
     ],
     "measurement": "Corona",
     "query": "SELECT last(\"Deaths\") AS \"metric\" FROM \"autogen\".\"Corona\" WHERE $timeFilter GROUP BY time(24h), \"country\", \"lat\", \"long\"",
     "select": [
      [
       { "params": [ "Deaths" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "metric" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Global Population Confirmed Ratio",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 14 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CoronaNew",
     "query": "SELECT 100* sum(Confirmed)/ 7781492808 FROM \"covid19\".\"autogen\".\"Corona\" WHERE $timeFilter GROUP BY time(24h) fill(null)",
     "select": [
      [
       { "params": [ "Confirmed" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " * 100 / 7781492808" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Confirmed Population Ratio Germany",
   "type": "singlestat",
   "description": "Percentage of the German population positive tested on Covid19.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 14 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Corona",
     "query": "SELECT last(\"Confirmed\")  * 100 / 82927922  FROM \"covid19\".\"autogen\".\"CoronaNew\" WHERE (\"country\" = 'Germany') AND $timeFilter GROUP BY time(24h) fill(null)",
     "select": [
      [
       { "params": [ "Confirmed" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " * 100 / 82927922 " ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "Germany" }
     ]
    }
   ]
  },
  {
   "title": "Death Population Ratio Germany",
   "type": "singlestat",
   "description": "Percentage of the German population died on Covid19.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 14 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Corona",
     "query": "SELECT last(\"Deaths\")  * 100 / 82927922  FROM \"covid19\".\"autogen\".\"CoronaNew\" WHERE (\"country\" = 'Germany') AND $timeFilter GROUP BY time(24h) fill(null)",
     "select": [
      [
       { "params": [ "Confirmed" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " * 100 / 82927922 " ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "Germany" }
     ]
    }
   ]
  },
  {
   "title": "Death Rate Germany",
   "type": "singlestat",
   "description": "Death rate of confirmed COVID-19 infections in Germany.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 14 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CoronaNew",
     "query": "SELECT 100*sum(\"Recovered\")/sum(Confirmed) FROM \"covid19\".\"autogen\".\"Corona\" WHERE $timeFilter GROUP BY time(24h) fill(null)\n",
     "select": [
      [
       { "params": [ "Deaths" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [
         " * 100 / \"Confirmed\""
        ],
        "type": "math"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "Germany" }
     ]
    }
   ]
  },
  {
   "title": "Confirmed Population Ratio China",
   "type": "singlestat",
   "description": "Percentage of the Chinese population positive tested on Covid19.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 14 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CoronaNew",
     "query": "SELECT sum(\"Confirmed\")  * 100 / 1392730000  FROM \"covid19\".\"autogen\".\"Corona\" WHERE $timeFilter GROUP BY time(24h) fill(null), country(Cina)",
     "select": [
      [
       { "params": [ "Confirmed" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " * 100 / 82927922 " ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "China" }
     ]
    }
   ]
  },
  {
   "title": "Death Population Ratio China",
   "type": "singlestat",
   "description": "Percentage of the Chinese population died on Covid19.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 14 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CoronaNew",
     "query": "SELECT sum(\"Confirmed\")  * 100 / 1392730000  FROM \"covid19\".\"autogen\".\"Corona\" WHERE $timeFilter GROUP BY time(24h) fill(null), country(Cina)",
     "select": [
      [
       { "params": [ "Deaths" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " * 100 / 82927922 " ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "China" }
     ]
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Corona",
     "query": " SELECT sum(\"Confirmed\") AS \"Confirmed\", sum(\"Deaths\") AS \"Deaths\", sum(\"Recovered\") AS \"Recovered\", \n100*sum(Deaths)/sum(Confirmed) as \"Fatality_Ratio\", 100*sum(Recovered)/sum(Confirmed) as \"Recovery_Ratio\", \nsum(\"Confirmed\")-sum(Deaths)-sum(Recovered) as \"Remaining\" FROM \"covid19\".\"autogen\".\"CoronaNew\" WHERE $timeFilter GROUP BY time(24h) fill(previous)",
     "select": [
      [
       { "params": [ "Confirmed" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Confirmed" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Confirmed",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_country",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Corona",
     "select": [
      [
       { "params": [ "Confirmed" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Deaths",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 30 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_country",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Corona",
     "select": [
      [
       { "params": [ "Deaths" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Recovered",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_country",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CoronaNew",
     "select": [
      [
       { "params": [ "Recovered" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Remaining",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 30 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_country",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CoronaNew",
     "query": "SELECT sum(\"Confirmed\") -sum(Death)-sum(Recovered) FROM \"covid19\".\"autogen\".\"Corona\" WHERE $timeFilter GROUP BY time(24h), \"country\" fill(null)",
     "select": [
      [
       { "params": [ "Confirmed" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [
         "-sum(\"Deaths\")-sum(\"Recovered\")"
        ],
        "type": "math"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Germany",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Confirmed",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CoronaNew",
     "query": "SELECT sum(\"Confirmed\") FROM \"covid19\".\"autogen\".\"Corona\" WHERE (\"country\" = 'Germany') AND $timeFilter GROUP BY time(24h), \"country\" fill(null)",
     "select": [
      [
       { "params": [ "Confirmed" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "Germany" }
     ]
    },
    {
     "alias": "Deaths",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CoronaNew",
     "select": [
      [
       { "params": [ "Deaths" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "Germany" }
     ]
    },
    {
     "alias": "Recovered",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CoronaNew",
     "select": [
      [
       { "params": [ "Recovered" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "Germany" }
     ]
    }
   ]
  },
  {
   "title": "Austria",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 36 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Confirmed",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CoronaNew",
     "query": "SELECT sum(\"Confirmed\") FROM \"covid19\".\"autogen\".\"Corona\" WHERE (\"country\" = 'Germany') AND $timeFilter GROUP BY time(24h), \"country\" fill(null)",
     "select": [
      [
       { "params": [ "Confirmed" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "Austria" }
     ]
    },
    {
     "alias": "Deaths",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CoronaNew",
     "select": [
      [
       { "params": [ "Deaths" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "Austria" }
     ]
    },
    {
     "alias": "Recovered",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CoronaNew",
     "select": [
      [
       { "params": [ "Recovered" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "Austria" }
     ]
    }
   ]
  },
  {
   "title": "Italy",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 36 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Confirmed",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CoronaNew",
     "query": "SELECT sum(\"Confirmed\") FROM \"covid19\".\"autogen\".\"Corona\" WHERE (\"country\" = 'Germany') AND $timeFilter GROUP BY time(24h), \"country\" fill(null)",
     "select": [
      [
       { "params": [ "Confirmed" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "Italy" }
     ]
    },
    {
     "alias": "Deaths",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CoronaNew",
     "select": [
      [
       { "params": [ "Deaths" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "Italy" }
     ]
    },
    {
     "alias": "Recovered",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CoronaNew",
     "select": [
      [
       { "params": [ "Recovered" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "Italy" }
     ]
    }
   ]
  },
  {
   "title": "Portugal",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Confirmed",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CoronaNew",
     "query": "SELECT sum(\"Confirmed\") FROM \"covid19\".\"autogen\".\"Corona\" WHERE (\"country\" = 'Germany') AND $timeFilter GROUP BY time(24h), \"country\" fill(null)",
     "select": [
      [
       { "params": [ "Confirmed" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "Portugal" }
     ]
    },
    {
     "alias": "Deaths",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CoronaNew",
     "select": [
      [
       { "params": [ "Deaths" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "Portugal" }
     ]
    },
    {
     "alias": "Recovered",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CoronaNew",
     "select": [
      [
       { "params": [ "Recovered" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "Portugal" }
     ]
    }
   ]
  },
  {
   "title": "Spain",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 42 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Confirmed",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CoronaNew",
     "query": "SELECT sum(\"Confirmed\") FROM \"covid19\".\"autogen\".\"Corona\" WHERE (\"country\" = 'Germany') AND $timeFilter GROUP BY time(24h), \"country\" fill(null)",
     "select": [
      [
       { "params": [ "Confirmed" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "Spain" }
     ]
    },
    {
     "alias": "Deaths",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CoronaNew",
     "select": [
      [
       { "params": [ "Deaths" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "Spain" }
     ]
    },
    {
     "alias": "Recovered",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CoronaNew",
     "select": [
      [
       { "params": [ "Recovered" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "Spain" }
     ]
    }
   ]
  },
  {
   "title": "China",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 42 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Confirmed",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CoronaNew",
     "query": "SELECT sum(\"Confirmed\") FROM \"covid19\".\"autogen\".\"Corona\" WHERE (\"country\" = 'Germany') AND $timeFilter GROUP BY time(24h), \"country\" fill(null)",
     "select": [
      [
       { "params": [ "Confirmed" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "China" }
     ]
    },
    {
     "alias": "Deaths",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CoronaNew",
     "select": [
      [
       { "params": [ "Deaths" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "China" }
     ]
    },
    {
     "alias": "Recovered",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CoronaNew",
     "select": [
      [
       { "params": [ "Recovered" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "China" }
     ]
    }
   ]
  }
 ]
}