{
 "title": "COVID-19 per Country",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Country",
    "label": "Country",
    "query": "SHOW TAG VALUES WITH KEY = \"country\""
   },
   { "name": "DS_CORONA", "query": "influxdb" }
  ]
 },
 "panels": [
  {
   "title": "Confirmed in $Country",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CoronaNew",
     "select": [
      [
       { "params": [ "Confirmed" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$Country$/" }
     ]
    }
   ]
  },
  {
   "title": "Deaths in $Country",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CoronaNew",
     "select": [
      [
       { "params": [ "Deaths" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$Country$/" }
     ]
    }
   ]
  },
  {
   "title": "Recovered in $Country",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CoronaNew",
     "select": [
      [
       { "params": [ "Recovered" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$Country$/" }
     ]
    }
   ]
  },
  {
   "title": "Remaining in $Country",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CoronaNew",
     "query": "SELECT sum(\"Confirmed\") -sum(Recovered)-sum(Deaths) FROM \"CoronaNew\" WHERE (\"country\" =~ /^$Country$/) AND $timeFilter GROUP BY time(24h) fill(null)",
     "select": [
      [
       { "params": [ "Confirmed" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "-sum(Recovered)-sum(Deaths)" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$Country$/" }
     ]
    }
   ]
  },
  {
   "title": "Fatality Ratio in $Country",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CoronaNew",
     "query": "SELECT sum(\"Deaths\") *100 / sum(\"Confirmed\") FROM \"covid19\".\"autogen\".\"CoronaNew\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Deaths" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [
         "*100 / sum(\"Confirmed\")"
        ],
        "type": "math"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$Country$/" }
     ]
    }
   ]
  },
  {
   "title": "Recovery Ratio in $Country",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CoronaNew",
     "query": "SELECT sum(\"Recovered\") * 100 / sum(\"Confirmed\" FROM \"covid19\".\"autogen\".\"CoronaNew\" WHERE $timeFilter GROUP BY time(24h) fill(null)",
     "select": [
      [
       { "params": [ "Recovered" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [
         "* 100 / sum(\"Confirmed\")"
        ],
        "type": "math"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$Country$/" }
     ]
    }
   ]
  },
  {
   "title": "$Country",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Confirmed",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CoronaNew",
     "query": "SELECT sum(\"Confirmed\") FROM \"covid19\".\"autogen\".\"CoronaNew\" WHERE (\"country\" = 'Germany') AND $timeFilter GROUP BY time(24h), \"country\" fill(null)",
     "select": [
      [
       { "params": [ "Confirmed" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$Country$/" }
     ]
    },
    {
     "alias": "Deaths",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CoronaNew",
     "select": [
      [
       { "params": [ "Deaths" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$Country$/" }
     ]
    },
    {
     "alias": "Recovered",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CoronaNew",
     "select": [
      [
       { "params": [ "Recovered" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$Country$/" }
     ]
    }
   ]
  },
  {
   "title": "$Country",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Confirmed",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CoronaNew",
     "select": [
      [
       { "params": [ "Confirmed" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$Country$/" }
     ]
    },
    {
     "alias": "Deaths",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CoronaNew",
     "select": [
      [
       { "params": [ "Deaths" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$Country$/" }
     ]
    },
    {
     "alias": "Recovered",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CoronaNew",
     "select": [
      [
       { "params": [ "Recovered" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$Country$/" }
     ]
    }
   ]
  },
  {
   "title": "Global",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Confirmed",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CoronaNew",
     "select": [
      [
       { "params": [ "Confirmed" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": "Deaths",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CoronaNew",
     "select": [
      [
       { "params": [ "Deaths" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": "Recovered",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CoronaNew",
     "select": [
      [
       { "params": [ "Recovered" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "New per day - $Country",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Confirmed",
     "measurement": "CoronaNew",
     "select": [
      [
       { "params": [ "ConfirmedNew" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$Country$/" }
     ]
    },
    {
     "alias": "Deaths",
     "measurement": "CoronaNew",
     "select": [
      [
       { "params": [ "DeathsNew" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$Country$/" }
     ]
    },
    {
     "alias": "Recovered",
     "measurement": "CoronaNew",
     "select": [
      [
       { "params": [ "RecoveredNew" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$Country$/" }
     ]
    }
   ]
  },
  {
   "title": "New per day - Global",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Confirmed",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" }
     ],
     "measurement": "CoronaNew",
     "select": [
      [
       { "params": [ "ConfirmedNew" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": "Deaths",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" }
     ],
     "measurement": "CoronaNew",
     "select": [
      [
       { "params": [ "DeathsNew" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": "Recovered",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" }
     ],
     "measurement": "CoronaNew",
     "select": [
      [
       { "params": [ "RecoveredNew" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Africa - Deaths",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_country",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CoronaNew",
     "query": "SELECT last(\"Deaths\") FROM \"covid19\".\"autogen\".\"CoronaNew\" WHERE (\"country\" = 'Germany' OR \"country\" = 'Italy' OR \"country\" = 'Poland' OR \"country\" = 'Spain') AND $timeFilter GROUP BY time(24h), \"country\" fill(null)",
     "select": [
      [
       { "params": [ "Deaths" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=", "value": "Africa" }
     ]
    }
   ]
  },
  {
   "title": "Americans - Deaths",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_country",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CoronaNew",
     "query": "SELECT last(\"Deaths\") FROM \"covid19\".\"autogen\".\"CoronaNew\" WHERE (\"country\" = 'Germany' OR \"country\" = 'Italy' OR \"country\" = 'Poland' OR \"country\" = 'Spain') AND $timeFilter GROUP BY time(24h), \"country\" fill(null)",
     "select": [
      [
       { "params": [ "Deaths" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=", "value": "Americas" }
     ]
    }
   ]
  },
  {
   "title": "Asia - Deaths",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_country",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CoronaNew",
     "query": "SELECT last(\"Deaths\") FROM \"covid19\".\"autogen\".\"CoronaNew\" WHERE (\"country\" = 'Germany' OR \"country\" = 'Italy' OR \"country\" = 'Poland' OR \"country\" = 'Spain') AND $timeFilter GROUP BY time(24h), \"country\" fill(null)",
     "select": [
      [
       { "params": [ "Deaths" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=", "value": "Asia" }
     ]
    }
   ]
  },
  {
   "title": "Europe - Deaths",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_country",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CoronaNew",
     "query": "SELECT last(\"Deaths\") FROM \"covid19\".\"autogen\".\"CoronaNew\" WHERE (\"country\" = 'Germany' OR \"country\" = 'Italy' OR \"country\" = 'Poland' OR \"country\" = 'Spain') AND $timeFilter GROUP BY time(24h), \"country\" fill(null)",
     "select": [
      [
       { "params": [ "Deaths" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=", "value": "Europe" }
     ]
    }
   ]
  },
  {
   "title": "Oceania - Deaths",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_country",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CoronaNew",
     "query": "SELECT last(\"Deaths\") FROM \"covid19\".\"autogen\".\"CoronaNew\" WHERE (\"country\" = 'Germany' OR \"country\" = 'Italy' OR \"country\" = 'Poland' OR \"country\" = 'Spain') AND $timeFilter GROUP BY time(24h), \"country\" fill(null)",
     "select": [
      [
       { "params": [ "Deaths" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "region", "operator": "=", "value": "Oceania" }
     ]
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 54 }, "content": "\n\n\n\n\n\n" }
 ]
}